//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShopUP
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSet
    {
        public int id_order { get; set; }
        public int id_staff { get; set; }
        public int id_customer { get; set; }
        public int id_product { get; set; }
    
        public virtual CustomerSet CustomerSet { get; set; }
        public virtual ProductsSet ProductsSet { get; set; }
        public virtual StaffSet StaffSet { get; set; }
    }
}
